Document: erms
Title: Debian erms Manual
Author: <insert document author here>
Abstract: This manual describes what erms is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/erms/erms.sgml.gz

Format: postscript
Files: /usr/share/doc/erms/erms.ps.gz

Format: text
Files: /usr/share/doc/erms/erms.text.gz

Format: HTML
Index: /usr/share/doc/erms/html/index.html
Files: /usr/share/doc/erms/html/*.html

  
